service: cloudformation-infra-creation
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: ${file(config/config.${opt:stage}.yml):region}
  deploymentPrefix: resource
resources:
  - ${file(./resources/ec2.yml)}
  - ${file(./resources/ecr.yml)}