service: cloudformation-infra-creation
frameworkVersion: '3'
configValidationMode: error
provider:
  name: aws
  deploymentMethod: direct
  region: ${file(config/config.${opt:stage}.yml):region}
  deploymentPrefix: resource
resources:
  Conditions: 
    IsQA: 
      Fn::Equals: 
        - ${opt:stage} 
        - qa
Resources:
  - ${file(./resources/ec2.yml)}
  - ${file(./resources/ecr.yml)}
  - ${file(./resources/parameter.yml)}
  

