---
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ${file(config/config.${opt:stage}.yml):ami}
      KeyName: ${file(config/config.${opt:stage}.yml):keyname}
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: My-Ec2-instance

  MyEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ${file(config/config.${opt:stage}.yml):ami}
      KeyName: ${file(config/config.${opt:stage}.yml):keyname}
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: My-Ec2-instance-1