---
Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-repository
      ImageScanningConfiguration:
        scanOnPush: true

  MyECRRepository1:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-repository-1
      ImageScanningConfiguration:
        scanOnPush: true