# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  Infra:
    environment: dev
    name: deploy infrastructure  
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      packages: write
      contents: read    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1
      - name: Installing serverless
        run: |
          npm install -g serverless
      - name: Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      # - name: authenticating to AWS
      #   run: sls config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: deploying infrastructure
        run: sls deploy --stage dev